TLOSolution.WebApp/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TLOSoltuion.Data.EF;
using TLOSolution.WebApp.Models;

namespace TLOSolution.WebApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly TLODbContext _context;

        public CategoryController(TLODbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var result = from p in _context.Post
                         where p.CategoryId == id
                         select p;
            if (result == null)
            {
                return View();
            }

            var posts = await result.Select(x => new PostViewModel()
            {
                Id = x.Id,
                Title = x.Title,
                Description = x.Description,
                DocumentPath = x.DocumentPath,
                CategoryName = x.Category.Name,
                PublisherName = x.User.FirstName + " " + x.User.LastName,
                DocumentType = x.DocumentType,
                DowloadCount = x.DowloadCount,
                ViewCount = x.ViewCount,
                ImagePath = x.ImagePath
            }).ToListAsync();

            var categories = from c in _context.Category
                             select c;

            var categoriesRes = await categories.Select(x => new CategoryViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                ImagePath = x.Imagepath
            }).ToListAsync();

            var CategoryDetail = new CategoryDetailViewModel()
            {   Categories = categoriesRes,
                Posts = posts
            };

            return View(CategoryDetail);
        }
    }
}

TLOSolution.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TLOSoltuion.Data.EF;
using TLOSolution.WebApp.Models;

namespace TLOSolution.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly TLODbContext _context;

        public HomeController(TLODbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var posts = from p in _context.Post
                        select p;

            var categories = from c in _context.Category
                             select c;

            var categoriesRes = await categories.Select(x => new CategoryViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                ImagePath = x.Imagepath
            }).ToListAsync();

            var postsRes = await posts.Select(x => new PostViewModel
            {
                Id = x.Id,
                Title = x.Title,
                Description = x.Description,
                DocumentPath = x.DocumentPath,
                CategoryName = x.Category.Name,
                PublisherName = x.User.FirstName + " " + x.User.LastName,
                DocumentType = x.DocumentType,
                DowloadCount = x.DowloadCount,
                ViewCount = x.ViewCount,
                ImagePath = x.ImagePath
            }).ToListAsync();

            var reponse = new SearchReponseViewModel
            {
                Categories = categoriesRes,
                Posts = postsRes
            };

            return View(reponse);
        }

        [HttpGet]
        public async Task<IActionResult> Search(SearchRequestViewModel request)
        {
            var categories = from c in _context.Category
                             select c;

            var categoriesRes = await categories.Select(x => new CategoryViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                ImagePath = x.Imagepath
            }).ToListAsync();

            var posts = from p in _context.Post
                        select p;

            if (!string.IsNullOrEmpty(request.InputString))
            {
                posts = posts.Where(p => p.Title.Contains(request.InputString));
            }

            if (request.CategoryId != null)
            {
                posts = posts.Where(p => p.CategoryId == request.CategoryId);
            }

            var postsRes = await posts.Select(x => new PostViewModel
            {
                Id = x.Id,
                Title = x.Title,
                Description = x.Description,
                DocumentPath = x.DocumentPath,
                CategoryName = x.Category.Name,
                PublisherName = x.User.FirstName + " " + x.User.LastName,
                DocumentType = x.DocumentType,
                DowloadCount = x.DowloadCount,
                ViewCount = x.ViewCount,
                ImagePath = x.ImagePath
            }).ToListAsync();

            var response = new SearchReponseViewModel() {
                Categories = categoriesRes,
                CategoryId = null,
                InputString = request.InputString,
                CategoryTitle = null,
                Posts = null
            };

            if (postsRes.Count == 0)
            {
                return View(response);
            }

            response = new SearchReponseViewModel()
            {
                Categories = categoriesRes,
                Posts = postsRes,
                CategoryId = request.CategoryId,
                CategoryTitle = postsRes[0].CategoryName,
                InputString = request.InputString
            };


            return View(response);
        }

        public async Task<IActionResult> Posts()
        {
            var posts = await _context.Post.ToListAsync();
            return View(posts);
        }
    }
}

TLOSolution.WebApp/Controllers/PostController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using TLOSoltuion.Data.EF;
using TLOSoltuion.Data.Entities;
using TLOSolution.WebApp.Models;

namespace TLOSolution.WebApp.Controllers
{
    public class PostController : Controller
    {
        private readonly TLODbContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public PostController(TLODbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var result = await _context.Post.Where(x => x.Id == id).FirstOrDefaultAsync();
            var user = await _context.Users.Where(x => x.Id == result.UserId).FirstOrDefaultAsync();
            if (result == null)
            {
                return View();
            }

            var categories = from c in _context.Category
                             select c;

            var categoriesRes = await categories.Select(x => new CategoryViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                ImagePath = x.Imagepath
            }).ToListAsync();

            var post = new PostDetailModel()
            {
                Categories = categoriesRes,
                Title = result.Title,
                Description = result.Description,
                DocumentPath = result.DocumentPath,
                DowloadCount = result.DowloadCount,
                PublisherName = user.FirstName + " " + user.LastName,
                ViewCount = result.ViewCount
            };

            result.ViewCount++;
            await _context.SaveChangesAsync();
            return View(post);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async void Create(PostCreateModel request)
        {
            if (!ModelState.IsValid)
            {
                return;
            }

            if (!await UploadFile(request.Document))
            {
                ModelState.AddModelError("", "cannot upload file");
                return;
            }

            var post = new Post()
            {
                Title = request.Title,
                Description = request.Description,
                DocumentPath = request.Document.FileName,
                DocumentType = request.Document.ContentType,
                ViewCount = 0,
                DowloadCount = 0,
                UserId = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier),
                CategoryId = request.CategoryId
            };

            await _context.Post.AddAsync(post);
            await _context.SaveChangesAsync();
        }

        private async Task<bool> UploadFile(IFormFile ufile)
        {
            if (ufile != null && ufile.Length > 0)
            {
                var fileName = Path.GetFileName(ufile.FileName);
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\content", fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await ufile.CopyToAsync(fileStream);
                }
                return true;
            }
            return false;
        }
    }
}

TLOSolution.WebApp/Views/Home/Index.cshtml
@model SearchReponseViewModel
@{
    ViewData["Title"] = "Trang chủ";
    var postList = Model.Posts;
    var categoryList = Model.Categories;
}

<div id="main">
    <div id="slider">
        <div>
            <img id="img" src="image/slider/1.jpg" alt="">
        </div>
    </div>
    <hr />

    <div id="content">

        <div class="first-content">
            <h1 class="first-content h1">DANH MỤC TÀI LIỆU</h1>
            <div class="container">
                <div class="row">
                    @foreach (var item in categoryList)
                    {
                        <div class="col-xs-15 col-sm-15 col-md-15 col-lg-15">
                            <a href="@Url.Action("Details", "Category", new { id = item.Id})" class="content-a">
                                <img class="img-item" src="@item.ImagePath" alt="">
                                <h3>@item.Name</h3>
                                <p>@item.Description</p>
                            </a>
                        </div>
                    }
                </div>
            </div>
        </div>
        <hr />

        <!-- Tất cả -->
        <div class="content-item">
            <h1 class="content-item h1">TẤT CẢ</h1>
            <div class="container">
                <div class="row">

                    @foreach (var item in postList)
                    {
                        <div class="col-xs-15 col-sm-15 col-md-15 col-lg-15 mh300">
                            <div class="box">
                                <a href="@Url.Action("Details", "Post", new { id = item.Id})" class="box-image">
                                    <i class="fas fa-file-word "></i>
                                    <img class="img-content-item" src="@item.ImagePath" alt=""></img>
                                </a>
                                <div class="box-item">
                                    <a href="@Url.Action("Details", "Post", new { id = item.Id})"><h4>@item.Title</h4></a>
                                    <ul class="content-item--ul">
                                        <li><i class="far fa-file-alt"> @*bỏ*@</i></li>
                                        <li><i class="fas fa-eye"></i>  @item.ViewCount</li>
                                        <li><i class="fas fa-download"> @item.DowloadCount</i></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <hr />

        <!-- Tài liệu chung -->
        <div class="content-last">
            <div class="container">
                <h1>TÀI LIỆU CHUNG</h1>
                <div class="content-last--item">
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
                            <h3 class="color color1">Ngoại Ngữ</h3>
                            <div class="content-last-list">
                                <a href="#">
                                    <i class="fas fa-file-word "></i>
                                    Viết đoạn văn ngắn tiếng anh về các chủ đề cho trước
                                    <ul class="content-item--ul pd20">
                                        <li><i class="far fa-file-alt"> 12</i></li>
                                        <li><i class="fas fa-eye"></i>  23,564</li>
                                        <li><i class="fas fa-download"> 560</i></li>
                                    </ul>
                                </a>
                            </div>
                            <div class="content-last-list">
                                <a href="#">
                                    <i class="fas fa-file-word "></i>
                                    Viết đoạn văn ngắn tiếng anh về các chủ đề cho trước
                                    <ul class="content-item--ul pd20">
                                        <li><i class="far fa-file-alt"> 12</i></li>
                                        <li><i class="fas fa-eye"></i>  23,564</li>
                                        <li><i class="fas fa-download"> 560</i></li>
                                    </ul>
                                </a>
                            </div>
                            <div class="content-last-list">
                                <a href="#">
                                    <i class="fas fa-file-word "></i>
                                    Viết đoạn văn ngắn tiếng anh về các chủ đề cho trước
                                    <ul class="content-item--ul pd20">
                                        <li><i class="far fa-file-alt"> 12</i></li>
                                        <li><i class="fas fa-eye"></i>  23,564</li>
                                        <li><i class="fas fa-download"> 560</i></li>
                                    </ul>
                                </a>
                            </div>

                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
                            <h3 class="color color2">Giáo Dục - Đào Tạo</h3>
                            <div class="content-last-list">
                                <a href="#">
                                    <i class="fas fa-file-word "></i>
                                    Viết đoạn văn ngắn tiếng anh về các chủ đề cho trước
                                    <ul class="content-item--ul pd20">
                                        <li><i class="far fa-file-alt"> 12</i></li>
                                        <li><i class="fas fa-eye"></i>  23,564</li>
                                        <li><i class="fas fa-download"> 560</i></li>
                                    </ul>
                                </a>
                            </div>
                            <div class="content-last-list">
                                <a href="#">
                                    <i class="fas fa-file-word "></i>
                                    Viết đoạn văn ngắn tiếng anh về các chủ đề cho trước
                                    <ul class="content-item--ul pd20">
                                        <li><i class="far fa-file-alt"> 12</i></li>
                                        <li><i class="fas fa-eye"></i>  23,564</li>
                                        <li><i class="fas fa-download"> 560</i></li>
                                    </ul>
                                </a>
                            </div>
                            <div class="content-last-list">
                                <a href="#">
                                    <i class="fas fa-file-word "></i>
                                    Viết đoạn văn ngắn tiếng anh về các chủ đề cho trước
                                    <ul class="content-item--ul pd20">
                                        <li><i class="far fa-file-alt"> 12</i></li>
                                        <li><i class="fas fa-eye"></i>  23,564</li>
                                        <li><i class="fas fa-download"> 560</i></li>
                                    </ul>
                                </a>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
                            <h3 class="color color3">Kỹ Thuật - Công Nghệ</h3>

                            <div class="content-last-list">
                                <a href="#">
                                    <i class="fas fa-file-word "></i>
                                    Viết đoạn văn ngắn tiếng anh về các chủ đề cho trước
                                    <ul class="content-item--ul pd20">
                                        <li><i class="far fa-file-alt"> 12</i></li>
                                        <li><i class="fas fa-eye"></i>  23,564</li>
                                        <li><i class="fas fa-download"> 560</i></li>
                                    </ul>
                                </a>
                            </div>
                            <div class="content-last-list">
                                <a href="#">
                                    <i class="fas fa-file-word "></i>
                                    Viết đoạn văn ngắn tiếng anh về các chủ đề cho trước
                                    <ul class="content-item--ul pd20">
                                        <li><i class="far fa-file-alt"> 12</i></li>
                                        <li><i class="fas fa-eye"></i>  23,564</li>
                                        <li><i class="fas fa-download"> 560</i></li>
                                    </ul>
                                </a>
                            </div>
                            <div class="content-last-list">
                                <a href="#">
                                    <i class="fas fa-file-word "></i>
                                    Viết đoạn văn ngắn tiếng anh về các chủ đề cho trước
                                    <ul class="content-item--ul pd20">
                                        <li><i class="far fa-file-alt"> 12</i></li>
                                        <li><i class="fas fa-eye"></i>  23,564</li>
                                        <li><i class="fas fa-download"> 560</i></li>
                                    </ul>
                                </a>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
                            <h3 class="color color4">Công Nghệ Thông Tin</h3>

                            <div class="content-last-list">
                                <a href="#">
                                    <i class="fas fa-file-word "></i>
                                    Viết đoạn văn ngắn tiếng anh về các chủ đề cho trước
                                    <ul class="content-item--ul pd20">
                                        <li><i class="far fa-file-alt"> 12</i></li>
                                        <li><i class="fas fa-eye"></i>  23,564</li>
                                        <li><i class="fas fa-download"> 560</i></li>
                                    </ul>
                                </a>
                            </div>
                            <div class="content-last-list">
                                <a href="#">
                                    <i class="fas fa-file-word "></i>
                                    Viết đoạn văn ngắn tiếng anh về các chủ đề cho trước
                                    <ul class="content-item--ul pd20">
                                        <li><i class="far fa-file-alt"> 12</i></li>
                                        <li><i class="fas fa-eye"></i>  23,564</li>
                                        <li><i class="fas fa-download"> 560</i></li>
                                    </ul>
                                </a>
                            </div>
                            <div class="content-last-list">
                                <a href="#">
                                    <i class="fas fa-file-word "></i>
                                    Viết đoạn văn ngắn tiếng anh về các chủ đề cho trước
                                    <ul class="content-item--ul pd20">
                                        <li><i class="far fa-file-alt"> 12</i></li>
                                        <li><i class="fas fa-eye"></i>  23,564</li>
                                        <li><i class="fas fa-download"> 560</i></li>
                                    </ul>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr />
    <!-- footer -->
</div>

TLOSolution.WebApp/Views/Home/Search.cshtml
@model SearchReponseViewModel
@{
    ViewData["Title"] = Model.InputString;
    var categories = Model.Categories;
    var posts = Model.Posts;
}

<main class="mt-73 main-bg">
    <div class="container">
        <p style="font-size: 25px;">Kết quả tìm kiếm với từ khóa "<strong>@Model.InputString</strong>"</p>
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="bg-white p-3 row">
            <div class="col-3">
                <div class="actived">
                    <a href="#" class="row text-decoration-none actived pt-1 pb-1">
                        <i class="fas fa-search col-1 mt-1 menu-text actived"></i>
                        <span class="col-6 text-dark hover actived">Tài liệu</span>
                    </a>
                </div>
            </div>
            <div class="col-8">

                @if (posts != null)
                {
                    foreach (var item in posts)
                    {
                        <div class="item row mb-3">
                            <div class="col-2">
                                <a href="@Url.Action("Details", "Post", new { id = item.Id})">
                                    <img src="@item.ImagePath" class="img-fluid">
                                </a>
                            </div>
                            <div class="col-10">
                                <a href="@Url.Action("Details", "Post", new { id = item.Id})" style="text-decoration: none; color: black; font-family: Roboto; font-size: 12px;">
                                    <h4>@item.Title</h4>
                                </a>
                                <p class="description">
                                    @item.Description
                                </p>
                                <div class="row col-5" style="font-size: 12px;">
                                    <div class="text-muted col-4">
                                        <i class="fas fa-eye"></i>
                                        <small>@item.ViewCount</small>
                                    </div>
                                    <div class="text-muted col-4">
                                        <i class="fas fa-download"></i>
                                        <small>@item.DowloadCount</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <span class="text-danger display-4">Không tìm thấy tài liệu</span>
                }

                <nav aria-label="Page navigation example" class="mt-5">
                    <ul class="pagination">
                        <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">Next</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</main>